# Generated by Django 6.0.7 on 2026-07-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_bu_counts', models.JSONField(blank=True, default=dict)),
                ('churn_manager_counts', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('total_renewals', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255)),
                ('bu_code', models.CharField(blank=True, max_length=100)),
                ('recharge_date', models.DateField(blank=True, null=True)),
                ('package', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('fiscal_year', models.CharField(blank=True, max_length=20)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('churn_days', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['recharge_date'], name='reports_ren_recharg_e01593_idx')],
            },
        ),
    ]
